apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: first
  name: database
spec:
  containers:
  - image: quay.io/mayank123modi/mysql
    name: first
    envFrom: 
    - secretRef: 
       name: mayank 
