apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test1
  name: test1
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: ClusterIP
status:
  loadBalancer: {}
