apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test2
  name: test2
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer
status:
  loadBalancer: {}
